#!/usr/bin/env python3
"""
render_report.py — store-review-check: JSON -> standalone HTML report.

Usage:
  python3 render_report.py report.json out.html [--open]

The JSON is produced by Claude after judging the checklist. Schema (all keys optional
except app/items):

{
  "lang": "en" | "ko" | "ja" | "zh",
  "app": "App name", "bundle_id": "com.example.app", "version": "1.0 (10)",
  "platforms": ["ios", "android"], "date": "2026-08-28",
  "project": "/path/to/project", "framework": "Flutter",
  "recurrence": [{"case": "2026-08-27-ios-1.2-ugc-jomhae", "ids": ["UGC-03", "UGC-04"]}],
  "profile": [{"feature": "Login", "value": "Google, Kakao", "evidence": "lib/auth.dart:12"}],
  "items": [{"id": "UGC-01", "status": "FAIL|WARN|UNKNOWN|PASS|NA",
             "guideline": "Apple 1.2 / Play UGC", "title": "No EULA consent",
             "state": "what exists / is missing", "evidence": "file:line",
             "fix": "how to fix", "proof": "what to record / configure"}],
  "priorities": ["Add Sign in with Apple (IOS-LOGIN-01 + ACC-03)", "..."],
  "console": {"ios": ["Privacy policy URL", "..."], "android": ["Data safety", "..."]},
  "review_notes": "text for App Review Information / App access",
  "repo": "https://github.com/LeeHueeng/store-review-check"
}
No third-party dependencies. Python 3.8+.
"""
import html
import json
import os
import re
import subprocess
import sys
import webbrowser

L10N = {
    "en": {
        "title": "Store Review Pre-Check Report", "app": "App", "version": "Version",
        "platforms": "Platforms", "date": "Checked on", "project": "Project", "framework": "Framework",
        "summary": "At a glance", "recurrence": "Recurrence risk — same pattern as a past rejection",
        "profile": "Feature profile (basis for judgments)", "feature": "Feature", "value": "Found",
        "evidence": "Evidence", "items": "Findings", "all": "All", "search": "Search ID, guideline, text…",
        "id": "ID", "status": "Status", "guideline": "Guideline", "summary_col": "Summary",
        "state": "Current state", "fix": "How to fix", "proof": "Proof / at submission",
        "priorities": "Fix priority", "console": "Console checklist (outside the code)",
        "ios": "App Store Connect", "android": "Google Play Console", "notes": "Review notes draft",
        "copy": "Copy", "copied": "Copied!", "generated": "Generated by", "print": "Print / PDF",
        "no_items": "No findings in this filter.",
        "FAIL": "FAIL", "WARN": "WARN", "UNKNOWN": "UNKNOWN", "PASS": "PASS", "NA": "N/A",
        "FAIL_d": "Will be rejected", "WARN_d": "Often rejected / console check", "UNKNOWN_d": "Needs verification",
        "PASS_d": "Verified OK", "NA_d": "Not applicable",
    },
    "ko": {
        "title": "스토어 심사 사전 점검 리포트", "app": "앱", "version": "버전",
        "platforms": "플랫폼", "date": "점검일", "project": "프로젝트", "framework": "프레임워크",
        "summary": "한눈에 보기", "recurrence": "재발 위험 — 과거 리젝과 같은 패턴",
        "profile": "기능 프로필 (판정 근거)", "feature": "기능", "value": "확인된 것",
        "evidence": "근거", "items": "판정 항목", "all": "전체", "search": "ID, 가이드라인, 내용 검색…",
        "id": "ID", "status": "등급", "guideline": "가이드라인", "summary_col": "요약",
        "state": "현재 상태", "fix": "수정 방법", "proof": "증빙 / 제출 시",
        "priorities": "수정 우선순위", "console": "제출 전 콘솔 체크 (코드 밖)",
        "ios": "App Store Connect", "android": "Google Play Console", "notes": "심사 노트 초안",
        "copy": "복사", "copied": "복사됨!", "generated": "생성", "print": "인쇄 / PDF",
        "no_items": "이 필터에 해당하는 항목이 없습니다.",
        "FAIL": "FAIL", "WARN": "WARN", "UNKNOWN": "UNKNOWN", "PASS": "PASS", "NA": "N/A",
        "FAIL_d": "리젝 확정 수준", "WARN_d": "자주 걸림 / 콘솔 확인", "UNKNOWN_d": "확인 필요",
        "PASS_d": "근거 확인됨", "NA_d": "해당 없음",
    },
    "ja": {
        "title": "ストア審査 事前チェックレポート", "app": "アプリ", "version": "バージョン",
        "platforms": "プラットフォーム", "date": "チェック日", "project": "プロジェクト", "framework": "フレームワーク",
        "summary": "概要", "recurrence": "再発リスク — 過去のリジェクトと同じパターン",
        "profile": "機能プロファイル（判定根拠）", "feature": "機能", "value": "検出",
        "evidence": "根拠", "items": "判定項目", "all": "すべて", "search": "ID・ガイドライン・本文を検索…",
        "id": "ID", "status": "判定", "guideline": "ガイドライン", "summary_col": "概要",
        "state": "現状", "fix": "修正方法", "proof": "証跡 / 提出時",
        "priorities": "修正の優先順位", "console": "提出前コンソールチェック（コード外）",
        "ios": "App Store Connect", "android": "Google Play Console", "notes": "審査ノート下書き",
        "copy": "コピー", "copied": "コピーしました", "generated": "生成", "print": "印刷 / PDF",
        "no_items": "このフィルタに該当する項目はありません。",
        "FAIL": "FAIL", "WARN": "WARN", "UNKNOWN": "UNKNOWN", "PASS": "PASS", "NA": "N/A",
        "FAIL_d": "リジェクト確実", "WARN_d": "頻出 / コンソール確認", "UNKNOWN_d": "要確認",
        "PASS_d": "確認済み", "NA_d": "対象外",
    },
    "zh": {
        "title": "商店审核预检报告", "app": "应用", "version": "版本",
        "platforms": "平台", "date": "检查日期", "project": "项目", "framework": "框架",
        "summary": "概览", "recurrence": "复发风险 — 与过去的被拒模式相同",
        "profile": "功能画像（判定依据）", "feature": "功能", "value": "检测到",
        "evidence": "依据", "items": "判定项", "all": "全部", "search": "搜索 ID、指南、内容…",
        "id": "ID", "status": "等级", "guideline": "指南", "summary_col": "摘要",
        "state": "当前状态", "fix": "修复方法", "proof": "证明 / 提交时",
        "priorities": "修复优先级", "console": "提交前控制台检查（代码之外）",
        "ios": "App Store Connect", "android": "Google Play Console", "notes": "审核备注草稿",
        "copy": "复制", "copied": "已复制", "generated": "生成", "print": "打印 / PDF",
        "no_items": "此筛选条件下没有项目。",
        "FAIL": "FAIL", "WARN": "WARN", "UNKNOWN": "UNKNOWN", "PASS": "PASS", "NA": "N/A",
        "FAIL_d": "必被拒", "WARN_d": "常被拒 / 控制台确认", "UNKNOWN_d": "需确认",
        "PASS_d": "已核实", "NA_d": "不适用",
    },
}
STATUSES = ["FAIL", "WARN", "UNKNOWN", "PASS", "NA"]
ICON = {"FAIL": "🔴", "WARN": "🟠", "UNKNOWN": "⚪", "PASS": "🟢", "NA": "▫️"}


def md(s):
    """Minimal markdown: escape, `code`, **bold**, newlines."""
    if s is None:
        return ""
    if isinstance(s, list):
        s = "\n".join(str(x) for x in s)
    s = html.escape(str(s))
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    return s.replace("\n", "<br>")


def norm_status(s):
    s = (s or "UNKNOWN").upper().replace("/", "")
    return s if s in STATUSES else "UNKNOWN"


def render(d):
    lang = d.get("lang", "en")
    t = L10N.get(lang, L10N["en"])
    items = [dict(i, status=norm_status(i.get("status"))) for i in d.get("items", [])]
    order = {s: n for n, s in enumerate(STATUSES)}
    items.sort(key=lambda i: (order[i["status"]], i.get("id", "")))
    counts = {s: sum(1 for i in items if i["status"] == s) for s in STATUSES}
    plats = d.get("platforms") or []
    repo = d.get("repo", "https://github.com/LeeHueeng/store-review-check")
    key = re.sub(r"[^a-z0-9]+", "-", f"{d.get('app','')}-{d.get('date','')}".lower())

    def esc(x):
        return html.escape(str(x)) if x is not None else ""

    rows = []
    for i in items:
        s = i["status"]
        rows.append(f"""
<tr class="row" data-status="{s}" data-text="{esc(' '.join(str(i.get(k,'')) for k in ('id','guideline','title','state','evidence','fix','proof')).lower())}">
  <td class="id"><code>{esc(i.get('id'))}</code></td>
  <td><span class="badge {s}">{ICON[s]} {t[s]}</span></td>
  <td class="gl">{md(i.get('guideline'))}</td>
  <td class="ttl">{md(i.get('title'))}</td>
  <td class="ev">{md(i.get('evidence'))}</td>
</tr>
<tr class="detail" data-status="{s}">
  <td colspan="5">
    <div class="detail-grid">
      <div><h4>{t['state']}</h4><p>{md(i.get('state')) or '—'}</p></div>
      <div><h4>{t['fix']}</h4><p>{md(i.get('fix')) or '—'}</p></div>
      <div><h4>{t['proof']}</h4><p>{md(i.get('proof')) or '—'}</p></div>
    </div>
  </td>
</tr>""")

    profile_rows = "".join(
        f"<tr><td>{md(p.get('feature'))}</td><td>{md(p.get('value'))}</td><td class='ev'>{md(p.get('evidence'))}</td></tr>"
        for p in d.get("profile", [])
    )
    rec = d.get("recurrence") or []
    rec_html = ""
    if rec:
        lis = "".join(
            f"<li><code>{esc(r.get('case'))}</code> → {', '.join('<code>'+esc(x)+'</code>' for x in r.get('ids', []))}</li>"
            for r in rec
        )
        rec_html = f'<section class="recurrence"><h2>⚠️ {t["recurrence"]}</h2><ul>{lis}</ul></section>'

    pri = "".join(f"<li>{md(p)}</li>" for p in d.get("priorities", []))
    console = d.get("console") or {}

    def checklist(name, lst):
        if not lst:
            return ""
        lis = "".join(
            f'<li><label><input type="checkbox" data-k="{key}-{name}-{n}"> <span>{md(x)}</span></label></li>'
            for n, x in enumerate(lst)
        )
        return f"<div class='col'><h3>{t[name]}</h3><ul class='checks'>{lis}</ul></div>"

    console_html = checklist("ios", console.get("ios")) + checklist("android", console.get("android"))
    tiles = "".join(
        f'<button class="tile {s}" data-filter="{s}"><div class="n">{counts[s]}</div><div class="l">{ICON[s]} {t[s]}</div><div class="d">{t[s+"_d"]}</div></button>'
        for s in STATUSES
    )
    plat_badges = "".join(f'<span class="plat">{ "🍎 iOS" if p=="ios" else "🤖 Android" if p=="android" else esc(p)}</span>' for p in plats)
    notes = d.get("review_notes") or ""

    return f"""<!doctype html>
<html lang="{esc(lang)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(t['title'])} — {esc(d.get('app',''))}</title>
<style>
:root{{--bg:#f6f7f9;--card:#fff;--fg:#1a1d21;--muted:#6b7280;--line:#e5e7eb;--accent:#2563eb;
--fail:#dc2626;--warn:#ea580c;--unk:#6b7280;--pass:#16a34a;--na:#9ca3af;--code:#eef2f7}}
@media(prefers-color-scheme:dark){{:root{{--bg:#0f1115;--card:#171a21;--fg:#e6e8eb;--muted:#9aa3ad;--line:#262b33;--code:#232833}}}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--fg);font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Apple SD Gothic Neo","Noto Sans KR","Hiragino Sans","Noto Sans JP","PingFang SC",sans-serif}}
.wrap{{max-width:1100px;margin:0 auto;padding:28px 20px 60px}}
header{{display:flex;flex-wrap:wrap;gap:12px 24px;align-items:flex-end;justify-content:space-between;margin-bottom:20px}}
h1{{font-size:26px;margin:0 0 4px}}h2{{font-size:18px;margin:32px 0 12px}}h3{{font-size:15px;margin:0 0 8px}}h4{{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);margin:0 0 4px}}
.meta{{color:var(--muted);font-size:13px;display:flex;flex-wrap:wrap;gap:4px 16px}}.meta b{{color:var(--fg);font-weight:600}}
.plat{{display:inline-block;background:var(--code);border-radius:999px;padding:2px 10px;font-size:12px;margin-right:6px}}
.tiles{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}}
.tile{{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px;text-align:left;cursor:pointer;color:var(--fg);font:inherit}}
.tile.active{{outline:2px solid var(--accent)}}.tile .n{{font-size:30px;font-weight:700;line-height:1}}.tile .l{{font-weight:600;margin-top:6px}}.tile .d{{font-size:12px;color:var(--muted)}}
.tile.FAIL .n{{color:var(--fail)}}.tile.WARN .n{{color:var(--warn)}}.tile.PASS .n{{color:var(--pass)}}.tile.UNKNOWN .n{{color:var(--unk)}}.tile.NA .n{{color:var(--na)}}
.card{{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px;overflow-x:auto}}
table{{width:100%;border-collapse:collapse;font-size:14px}}th,td{{text-align:left;padding:9px 10px;border-top:1px solid var(--line);vertical-align:top}}th{{border-top:0;color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.04em}}
tr.row{{cursor:pointer}}tr.row:hover td{{background:rgba(37,99,235,.05)}}tr.detail{{display:none}}tr.detail.open{{display:table-row}}tr.detail td{{background:rgba(37,99,235,.04);border-top:0}}
.detail-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;padding:4px 0}}
.badge{{display:inline-block;border-radius:999px;padding:2px 10px;font-size:12px;font-weight:700;white-space:nowrap;color:#fff}}
.badge.FAIL{{background:var(--fail)}}.badge.WARN{{background:var(--warn)}}.badge.UNKNOWN{{background:var(--unk)}}.badge.PASS{{background:var(--pass)}}.badge.NA{{background:var(--na)}}
code{{background:var(--code);border-radius:5px;padding:1px 5px;font-size:.92em;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}
td.ev,td.id{{white-space:nowrap;max-width:260px;overflow:hidden;text-overflow:ellipsis}}td.ev{{font-size:13px;color:var(--muted)}}
.toolbar{{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:10px}}
.toolbar input{{flex:1;min-width:220px;padding:8px 12px;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--fg);font:inherit}}
.btn{{border:1px solid var(--line);background:var(--card);color:var(--fg);border-radius:8px;padding:7px 12px;cursor:pointer;font:inherit;font-size:13px}}.btn.active{{background:var(--accent);color:#fff;border-color:var(--accent)}}
.recurrence{{background:rgba(220,38,38,.08);border:1px solid rgba(220,38,38,.35);border-radius:12px;padding:12px 16px;margin-top:16px}}.recurrence h2{{margin:0 0 6px;font-size:16px}}
.cols{{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}}ul.checks{{list-style:none;padding:0;margin:0}}ul.checks li{{padding:5px 0;border-top:1px solid var(--line)}}ul.checks label{{display:flex;gap:8px;cursor:pointer}}ul.checks input:checked+span{{text-decoration:line-through;color:var(--muted)}}
pre{{white-space:pre-wrap;word-break:break-word;background:var(--code);padding:14px;border-radius:10px;font-size:13px;margin:0}}
ol.pri li{{margin:6px 0}}footer{{margin-top:40px;color:var(--muted);font-size:12px}}a{{color:var(--accent)}}
.empty{{color:var(--muted);padding:16px;text-align:center}}
@media print{{.toolbar,.tile,.btn{{display:none}}tr.detail{{display:table-row!important}}.card{{border:0}}body{{background:#fff}}}}
</style>
</head>
<body><div class="wrap">
<header>
  <div>
    <h1>{esc(t['title'])}</h1>
    <div class="meta">
      <span><b>{esc(d.get('app',''))}</b> {('<code>'+esc(d.get('bundle_id'))+'</code>') if d.get('bundle_id') else ''}</span>
      <span>{t['version']}: <b>{esc(d.get('version','—'))}</b></span>
      <span>{t['date']}: <b>{esc(d.get('date','—'))}</b></span>
      <span>{t['framework']}: <b>{esc(d.get('framework','—'))}</b></span>
      <span>{t['project']}: <code>{esc(d.get('project','—'))}</code></span>
    </div>
    <div style="margin-top:8px">{plat_badges}</div>
  </div>
  <button class="btn" onclick="window.print()">🖨 {t['print']}</button>
</header>

<h2>{t['summary']}</h2>
<div class="tiles">{tiles}</div>
{rec_html}

{('<h2>'+t['profile']+'</h2><div class="card"><table><thead><tr><th>'+t['feature']+'</th><th>'+t['value']+'</th><th>'+t['evidence']+'</th></tr></thead><tbody>'+profile_rows+'</tbody></table></div>') if profile_rows else ''}

<h2>{t['items']} <span style="color:var(--muted);font-weight:400;font-size:14px">({len(items)})</span></h2>
<div class="toolbar">
  <button class="btn active" data-filter="ALL">{t['all']}</button>
  {''.join(f'<button class="btn" data-filter="{s}">{ICON[s]} {t[s]} {counts[s]}</button>' for s in STATUSES)}
  <input id="q" type="search" placeholder="{esc(t['search'])}">
</div>
<div class="card">
<table id="items">
<thead><tr><th>{t['id']}</th><th>{t['status']}</th><th>{t['guideline']}</th><th>{t['summary_col']}</th><th>{t['evidence']}</th></tr></thead>
<tbody>{''.join(rows)}</tbody>
</table>
<div class="empty" id="empty" style="display:none">{t['no_items']}</div>
</div>

{('<h2>'+t['priorities']+'</h2><div class="card"><ol class="pri">'+pri+'</ol></div>') if pri else ''}

{('<h2>'+t['console']+'</h2><div class="card cols">'+console_html+'</div>') if console_html else ''}

{('<h2>'+t['notes']+' <button class="btn" id="copy">'+t['copy']+'</button></h2><div class="card"><pre id="notes">'+esc(notes)+'</pre></div>') if notes else ''}

<footer>{t['generated']} <a href="{esc(repo)}">store-review-check</a> · {esc(d.get('date',''))}</footer>
</div>
<script>
(function(){{
  var f='ALL', q='';
  function apply(){{
    var rows=document.querySelectorAll('#items tbody tr.row'), shown=0;
    rows.forEach(function(r){{
      var ok=(f==='ALL'||r.dataset.status===f)&&(!q||r.dataset.text.indexOf(q)>=0);
      r.style.display=ok?'':'none'; var dt=r.nextElementSibling; if(dt&&!ok){{dt.classList.remove('open')}} if(ok)shown++;
    }});
    document.getElementById('empty').style.display=shown?'none':'';
    document.querySelectorAll('[data-filter]').forEach(function(b){{b.classList.toggle('active',b.dataset.filter===f)}});
  }}
  document.querySelectorAll('[data-filter]').forEach(function(b){{b.addEventListener('click',function(){{f=b.dataset.filter;apply();window.scrollTo({{top:document.getElementById('items').getBoundingClientRect().top+window.scrollY-80,behavior:'smooth'}})}})}});
  document.getElementById('q').addEventListener('input',function(e){{q=e.target.value.toLowerCase();apply()}});
  document.querySelectorAll('#items tr.row').forEach(function(r){{r.addEventListener('click',function(){{r.nextElementSibling.classList.toggle('open')}})}});
  document.querySelectorAll('ul.checks input').forEach(function(c){{
    try{{c.checked=localStorage.getItem(c.dataset.k)==='1'}}catch(e){{}}
    c.addEventListener('change',function(){{try{{localStorage.setItem(c.dataset.k,c.checked?'1':'0')}}catch(e){{}}}});
  }});
  var cp=document.getElementById('copy'); if(cp){{cp.addEventListener('click',function(){{
    var txt=document.getElementById('notes').textContent;
    (navigator.clipboard?navigator.clipboard.writeText(txt):Promise.reject()).then(function(){{cp.textContent='{t["copied"]}';setTimeout(function(){{cp.textContent='{t["copy"]}'}},1500)}},function(){{}});
  }})}}
  apply();
}})();
</script>
</body></html>"""


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) < 2:
        print(__doc__)
        sys.exit(1)
    src, out = args[0], args[1]
    with open(src, encoding="utf-8") as fh:
        data = json.load(fh)
    page = render(data)
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"wrote {out} ({len(page)//1024} KB)")
    if "--open" in sys.argv:
        path = os.path.abspath(out)
        try:
            if sys.platform == "darwin":
                subprocess.run(["open", path], check=False)
            elif os.name == "nt":
                os.startfile(path)  # type: ignore[attr-defined]
            else:
                subprocess.run(["xdg-open", path], check=False)
        except Exception:
            webbrowser.open("file://" + path)


if __name__ == "__main__":
    main()
